name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      run: apt-get install -y nuget mono-devel mono-xbuild
      run: nuget update -self
      run: nuget restore
    - name: Restore dependencies
      run: nuget restore
    - name: Build
      run: xbuild Raspberryio-HC-SR04.sln
